name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**Makefile"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build_test:
    strategy:
      matrix:
        projects: [3coloring, forkFFT, mygrep]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cd ${{ matrix.projects }} && make
